# DO NOT EDIT THIS FILE --- This file is a managed file, do not edit it directly.

set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ".elf")

target_compile_options(${PROJECT_NAME} PUBLIC
    ${CPU_FLAGS}
    ${CC_SECURE}
    # Compiler flags specific to Debug build type
    $<$<CONFIG:Debug>:
      $<$<COMPILE_LANGUAGE:C>: 
        -std=gnu11
        -fstack-usage
        -Wall
        -Wextra
        -Wpedantic
        -Wno-unused-parameter
        -O0
        -g3
        -ggdb
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        -std=gnu11
        -fstack-usage
        -Wall
        -Wextra
        -Wpedantic
        -Wno-unused-parameter
        -O0
        -g3
        -ggdb
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        -std=gnu11
        -fstack-usage
        -Wall
        -Wextra
        -Wpedantic
        -Wno-unused-parameter
        -O0
        -g3
        -ggdb
        -x
        assembler-with-cpp
        -MMD
        -MP
      >
    >

    # Compiler flags specific to Release build type
    $<$<CONFIG:Release>:
      $<$<COMPILE_LANGUAGE:C>: 
        -std=gnu11
        -fstack-usage
        -Wall
        -Wextra
        -Wpedantic
        -Wno-unused-parameter
        -Os
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        -std=gnu11
        -fstack-usage
        -Wall
        -Wextra
        -Wpedantic
        -Wno-unused-parameter
        -Os
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        -std=gnu11
        -fstack-usage
        -Wall
        -Wextra
        -Wpedantic
        -Wno-unused-parameter
        -Os
        -x
        assembler-with-cpp
        -MMD
        -MP
      >
    >

)

target_include_directories(${PROJECT_NAME} PUBLIC 
    "${CMAKE_CURRENT_SOURCE_DIR}/Inc"
)

target_compile_definitions(${PROJECT_NAME} PUBLIC 
    # Symbols specific to Debug build type
    $<$<CONFIG:Debug>: 
      $<$<COMPILE_LANGUAGE:C>: 
        RTE_DEVICE_STARTUP_STM32F4XX
        DEBUG
      >

      $<$<COMPILE_LANGUAGE:CXX>: 
        RTE_DEVICE_STARTUP_STM32F4XX
        DEBUG
      >
    
      $<$<COMPILE_LANGUAGE:ASM>: 
        RTE_DEVICE_STARTUP_STM32F4XX
        DEBUG
      >
    >

    
    # Symbols specific to Release build type
    $<$<CONFIG:Release>: 
      $<$<COMPILE_LANGUAGE:C>: 
        RTE_DEVICE_STARTUP_STM32F4XX
      >

      $<$<COMPILE_LANGUAGE:CXX>: 
        RTE_DEVICE_STARTUP_STM32F4XX
      >
    
      $<$<COMPILE_LANGUAGE:ASM>: 
        RTE_DEVICE_STARTUP_STM32F4XX
      >
    >

    
)

target_link_options(${PROJECT_NAME} PUBLIC 
    ${CPU_FLAGS}
    ${CC_SECURE}

    # Linker flags specific to Debug build type
    $<$<CONFIG:Debug>: 
        -T${CMAKE_CURRENT_BINARY_DIR}/stm32f407xe_flash.ld
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/car.map
        -u
        _printf_float
        --specs=nosys.specs
        -Wl,--start-group
        -lc
        -lm
        -lstdc++
        -lsupc++
        -Wl,--end-group
        -Wl,-z,max-page-size=8
        -Wl,--print-memory-usage
    >

    # Linker flags specific to Release build type
    $<$<CONFIG:Release>: 
        -T${CMAKE_CURRENT_BINARY_DIR}/stm32f407xe_flash.ld
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/car.map
        -u
        _printf_float
        --specs=nosys.specs
        -Wl,--start-group
        -lc
        -lm
        -lstdc++
        -lsupc++
        -Wl,--end-group
        -Wl,-z,max-page-size=8
        -Wl,--print-memory-usage
    >

)
# Clean .map file
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/${PROJECT_NAME}.map")
