# DO NOT EDIT THIS FILE --- This file is a managed file, do not edit it directly.
set(CMSIS_Dvendor STMicroelectronics:13)
set(CMSIS_Dname STM32F407VET6)
set(CMSIS_Dcore Cortex-M4)
set(CMSIS_Dfpu SP_FPU)
set(CMSIS_Ddsp DSP)
set(CMSIS_Dmve NO_MVE)
set(CMSIS_Dendian Little-endian)
set(CMSIS_Tcompiler GCC)

# Set target definition variables needed for the TOOLCHAIN_FILE
set(CPU ${CMSIS_Dcore})
set(FPU ${CMSIS_Dfpu})
set(DSP ${CMSIS_Ddsp})
set(MVE ${CMSIS_Dmve})
set(BYTE_ORDER ${CMSIS_Dendian})
